---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: application-ee395aff-d90c-ea4e-b24c-5f3d09e427d2
  name: myapp-prod-something-env-variables
  labels:
    tenant: Dolittle
    application: MyApp-Prod
    microservice: Something
data:
  NODE_ENV: "production"
  DATABASE_HOST: "myapp-prod-mongo.application-ee395aff-d90c-ea4e-b24c-5f3d09e427d2.svc.cluster.local"
  DATABASE_NAME: "read_models_something"
  EVENTSTORE_HOST: "myapp-prod-mongo.application-ee395aff-d90c-ea4e-b24c-5f3d09e427d2.svc.cluster.local"
  EVENTSTORE_NAME: "event_store_something"
  DOLITTLE_RUNTIME_HOST: "localhost"
  DOLITTLE_RUNTIME_PORT: "50053"
  PORT: "80"

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: application-ee395aff-d90c-ea4e-b24c-5f3d09e427d2
  name: myapp-prod-something-config-files
  labels:
    tenant: Dolittle
    application: MyApp-Prod
    microservice: Something
data:
